### ISSUE TITLE
Win/Losing should be at the end.

### ISSUE THREAD

**Issue by cheukyin699** [ubclaunchpad/ubcsim2#123]
**Describe the bug**
Winning and losing should only happen at the end of the game. You shouldn't be able to lose and not come back from it.

We also want to have a button that refreshes the page when the game ends.

Weeks also shouldn't pass in the middle of conversations.

**Comment by tonywu94** [comment]
The progress bar also needs to know the total number of weeks. It is currently hardcoded to 5 or whatever weeks. If there is a way to determine that from the JSON that would be great.

**Comment by cheukyin699** [comment]
Got it. Will be adding a constant somewhere.
