### ISSUE TITLE
set up ubcsim2.ubclaunchpad.com

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/ubcsim2#141]
I can set up a CNAME record pointing https://ubcsim2.ubclaunchpad.com to this repo's `gh-pages`, which might be a nicer URL than https://ubclaunchpad.github.io/ubcsim2, if nobody has any objections

**Comment by cheukyin699** [comment]
No objectives here

**Comment by bobheadxi** [comment]
the site is live at https://ubcsim2.ubclaunchpad.com! let me know if there are any issues
