### ISSUE TITLE
Create UI Wireframes for Mobile and Desktop

### ISSUE THREAD

**Issue by tonywu94** [ubclaunchpad/ubcsim2#23]
**What aspect of design do you want changed or added to?**
The mobile game UI 

**Why do you want this changed or added?**
Create many UI that seems to add/improve to the original UBC Sim

**How would you like to change or add to the design?**
Prototype in Figma

**Comment by rmcreyes** [comment]
Can this be closed? Do we know what the app is supposed to look like on mobile and desktop yet?
