### ISSUE TITLE
Deploy to GitHub pages

### ISSUE THREAD

**Issue by rmcreyes** [ubclaunchpad/ubcsim2#25]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
We need a mechanism for compiling our Typescript and deploying our project to GitHub pages.

**Describe the solution you'd like**
This [page](https://docs.travis-ci.com/user/deployment/pages/) details how to do this.

**Comment by eloisepeng** [comment]
you can read how to set up ts and deploy to gitpages here 
- https://zubialevich.blogspot.com/2018/09/how-to-build-typescript-github-pages-app.html
