### ISSUE TITLE
Detail the list of official events

### ISSUE THREAD

**Issue by rmcreyes** [ubclaunchpad/ubcsim2#37]
**Describe the area of the project that could be documented better**
Once we have the logic set up for going through the game, we need to start implementing the actual events. We need to easily be able to refer to what events we actually need to implement.

**What kind of questions would you like answered?**
Where can I see a list of events we need to implement?

**Comment by tonywu94** [comment]
Created a spreadsheet for inventory of events on[ Google Drive](https://docs.google.com/spreadsheets/d/1AxO6YEhcv2S57z-QKf2Ep7hDsxFbXGYfdqPQw-u-cqU/edit#gid=0)
