### ISSUE TITLE
Study how we can add minigames to our project

### ISSUE THREAD

**Issue by rmcreyes** [ubclaunchpad/ubcsim2#39]
**Point out a topic we should study up on before implementing**
We plan on adding minigames to our project, but we don't know how yet.

**Detail any specific questions we have about the topic**
Where would we put our code for the minigames?
How much common code can we have for minigames?

**Comment by cheukyin699** [comment]
With our current manpower and momentum, I don't think we are able to take on a completely new game concept. However, we can probably adapt minigames from other places.

- Dino run

If we want to use the current code for minigames, it would just be i>clicker multiple choice style games, which can be engaging if used in the right context.

If we are using HTML Canvas along with React, the code shouldn't be too different from just JS on HTML Canvas; if anything, it might be slightly less boiler plate.
