### ISSUE TITLE
Conditionally end the week based off event chain

### ISSUE THREAD

**Issue by rmcreyes** [ubclaunchpad/ubcsim2#58]
**Is your feature request related to a problem? Please describe.**
We currently assume that each week strictly corresponds to one event, but a chain of events like in #48 could contradict this.

**Describe the solution you'd like**
Develop a mechanism for ending the week conditionally.

**Additional context**
This is a bit open ended. A possible idea is just adding a flag to each choice indicating whether or not the choice would end the week, other ideas are welcome as well.

**Comment by cheukyin699** [comment]
Closed in favour of #101
