### ISSUE TITLE
Implement a win/lose condition

### ISSUE THREAD

**Issue by rmcreyes** [ubclaunchpad/ubcsim2#67]
**Is your feature request related to a problem? Please describe.**
It is currently impossible to end the game.

**Describe the solution you'd like**
Create a function that, given the current player stats, determines whether or not the player ends the game. If they do, move the player to some kind of end-game event.

**Comment by cheukyin699** [comment]
Temporarily set the win condition to if the user survives 5 weeks because we don't have enough events to accommodate. Set the lose condition to < 1.0 GPA.
