### ISSUE TITLE
[EVENT] Lose event

### ISSUE THREAD

**Issue by rmcreyes** [ubclaunchpad/ubcsim2#68]
**Main Prompt**
What is the question that needs to be asked to the player?
Oops, you didn't survive UBC...

**Choices**
Detail the choices the player can choose, and the changes this makes to the game session

Choice 1: Play again
- Player stat changes:
  - GPA: +0
  - Sleep: +0
  - Friends: +0
- Follow up event issue number (if applicable): #
- Minigame issue number (if applicable): #

**Note**: Have this choice restart the game

**Comment by cheukyin699** [comment]
Covered in #67. Closing.
