### ISSUE TITLE
Create a Google form for crowd sourcing event ideas

### ISSUE THREAD

**Issue by rmcreyes** [ubclaunchpad/ubcsim2#70]
**What aspect of design do you want changed or added to?**
It's hard to come up with creative event ideas all by ourselves 😢 

**How would you like to change or add to the design?**
Create a Google form where anyone can suggest an idea for an event. At minimum, ask for the information required by our event detail issue template to make porting of ideas to actual issues easier. Also add a link to this form in the `README.md` for easy access.

**Comment by tonywu94** [comment]
It's up on Google Drive!
