### ISSUE TITLE
Borders of boxes don't look nice on Android

### ISSUE THREAD

**Issue by cheukyin699** [ubclaunchpad/ubcsim2#87]
**Describe the bug**
Borders on boxes look weird on Android. Maybe an issue with screen sizes as well.

**Root Cause**
???

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tonywu94** [comment]
I got rid of the nes css framework last week and it should fixed things.
