### ISSUE TITLE
Change the faculty icon to HTML instead of PNG

### ISSUE THREAD

**Issue by tonywu94** [ubclaunchpad/ubcsim2#90]
**Is your feature request related to a problem? Please describe.**

I want to change the Faculty icon from an image to HTML.

**Describe the solution you'd like**

What I want is for the faculty icon to be a fixed div. When you choose a faculty, this will change the css background-color and the text inside. This is currently an image at this point. 

**Additional context**

![Screen Shot 2020-01-25 at 3 13 31 PM](https://user-images.githubusercontent.com/22286446/73128511-4f307f00-3f85-11ea-8113-cd5fed75ad5a.png)

**Comment by eloisepeng** [comment]
I think we can close this issue now since @tonywu94 's last commit #126
