### ISSUE TITLE
Stat UI - On change animation

### ISSUE THREAD

**Issue by tonywu94** [ubclaunchpad/ubcsim2#91]
**Is your feature request related to a problem? Please describe.**

When the score is updated, there should be some kind of animation to indicate to the user that the score has changed.

**Describe the solution you'd like**

The exact animation will worked out. Let's start by changing the score to GREEN if the score increases, and RED if the score decreases.

**Additional context**

**Comment by rmcreyes** [comment]
In the case where we want fancy animations, this may be a useful library to use: https://www.react-spring.io/
